[hooks]
pre-commit = [
    "cargo fmt --all",
    "cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic -A clippy::missing_docs_in_private_items -A clippy::module_name_repetitions",
    "cargo test --all-features"
]

[hooks.pre-push]
commands = [
    "cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic -A clippy::missing_docs_in_private_items -A clippy::module_name_repetitions",
    "cargo test --all-features"
]

[logging]
verbose = true

